### ISSUE TITLE
version 1.1.2 does not include webserver support despite documentation

### ISSUE THREAD

**Issue by andreabisiach** [orctom/was-gradle-plugin#2]
Hello,

I have included the plugin using the following:
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.orctom.gradle.was:was-gradle-plugin:1.1.2"
  }
}

the property webservers =  is totally ignored.
If I download the Jython from her https://github.com/orctom/was-util/blob/master/src/main/resources/jython/websphere.py and specify it using "script =" then webservers are applied.
it seems that a new verison of the plug-in should be published on https://plugins.gradle.org/m2

**Comment by orctom** [comment]
It is published. 
Not sure why it's not set to the default version on the plugin portal
https://plugins.gradle.org/plugin/com.orctom.was/1.1.3.2
